feat: Enable querying multiple LibraryItem types at once
equinor/procosys-completion-api pull request #103
Opened 2024-02-23 09:52 UTC by Hatleskog

2024-02-23 11:02 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/LibraryItemDto.cs
> +using Equinor.ProCoSys.Completion.Domain.AggregateModels.LibraryAggregate;
remove

2024-02-23 11:42 UTC, Hatleskog commented on src/tests/Equinor.ProCoSys.Completion.Query.Tests/LibraryItemQueries/GetLibraryItems/GetLibraryItemsQueryHandlerTests.cs
Will fix that

2024-02-26 06:48 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.IntegrationTests/LibraryItems/LibraryItemsControllerNegativeTests.cs
> +            [LibraryType.PUNCHLIST_SORTING, LibraryType.PUNCHLIST_PRIORITY],
It's OK, but since these tests are negative tests, you didn't have to pass 2 values. The test was good as it was, passing 1 value (you don't have to undo)

2024-02-26 07:00 UTC, janid1967 requested changes
The only change I like to be done in integration test project is to pass parameter to GetLibraryItemsAsync in plural. All other changes in integration test project belong in project Equinor.ProCoSys.Completion.Query.Tests.LibraryItemQueries.GetLibraryItems.GetLibraryItemsQueryHandlerTests

Integration tests test that the controller work, returning something in positive tests and return correct status in negative tests. 
Tests in Equinor.ProCoSys.Completion.Query should test the business logic.

Tests in Equinor.ProCoSys.Completion.Query.Tests.LibraryItemQueries.GetLibraryItems.GetLibraryItemsQueryHandlerTests should now have test methods:
* Handler_ShouldReturnCorrectNumberOfLibraryItems_WhenQueryingSingleType (rename existing Handler_ShouldReturnCorrectNumberOfLibraryItems())
* Handler_ShouldReturnCorrectNumberOfLibraryItems_WhenQueryingMultipleTypes

2024-02-26 10:32 UTC, janid1967 approved these changes

2024-02-26 12:58 UTC, merged