Add sas url to attachments
equinor/procosys-completion-api pull request #108
Opened 2024-03-04 12:53 UTC by Hatleskog

2024-03-04 13:14 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
> +        string? fromIPAddress = null,
Rename IPAddress to IpAddress for all variables in this class (my Resharper complains)

2024-03-04 13:18 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
> +            return new
Reformat to break long line into one param each line + to expression lambda + return on line 114 can be expression body. Result:
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/9b4c0c2b-8803-439a-9b5e-811b7e81a519)

2024-03-04 13:19 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
> +            , x.GetFullBlobPath()
reformat to have comma on end of line instead of beginning of line

2024-03-04 13:21 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/PunchItemQueries/GetPunchItemAttachments/GetPunchItemAttachmentsQuery.cs
> +    public string? FromIPAddress { get; }
Rename IP to Ip

2024-03-04 13:32 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Query.Tests/Attachments/AttachmentServiceTests.cs
> +        _webHostEnvironmentMock.EnvironmentName.Returns(Environments.Production);
Returning EnvironmentName has no effect. Delete line

2024-03-04 13:42 UTC, janid1967 requested changes
See comments

2024-03-04 13:45 UTC, janid1967 commented
@Hatleskog I guess the reason for this change is to avoid asking backend for sasuri for each attachment after getting list of attachments via GetAllForParentAsync?

2024-03-04 13:55 UTC, Hatleskog commented
> @Hatleskog I guess the reason for this change is to avoid asking backend for sasuri for each attachment after getting list of attachments via GetAllForParentAsync?

Yes, any objections?

2024-03-04 13:58 UTC, janid1967 commented
> > @Hatleskog I guess the reason for this change is to avoid asking backend for sasuri for each attachment after getting list of attachments via GetAllForParentAsync?
> 
> Yes, any objections?

No, but then all code for IAttachmentService.GetDownloadUriAsync should be removed .. all tests and everything

2024-03-04 13:59 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/IAttachmentsService.cs
> +        CancellationToken cancellaionToken,
fix misspelling

2024-03-05 06:15 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Query.Tests/Attachments/AttachmentServiceTests.cs
> +using Microsoft.Extensions.Hosting;
remove

2024-03-05 06:21 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
> +            new DateTimeOffset(now.AddMinutes(_blobStorageOptions.Value.BlobClockSkewMinutes * -1)),
we should discuss if we need both BlobClockSkewMinutes  and the new stuff using fromIpAddress / toIpAddress
The BlobClockSkewMinutes  value are default set to 3 minutes. That mean that the url is still valid in 3 minutes.
Since client now will get all attachments with all sasuri's in one go, what will happen if client wait for 4 minutes and click on the picture? .... or are all attachments downloaded to client before those 3 minutes has passed?

2024-03-05 06:37 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/PunchItemQueries/GetPunchItemAttachments/GetPunchItemAttachmentsQuery.cs
> +    public GetPunchItemAttachmentsQuery(Guid punchItemGuid, string? fromIpAddress, string? toIpAddress) => (PunchItemGuid, FromIpAddress, ToIpAddress) = (punchItemGuid, fromIpAddress, toIpAddress);
long line ... split on =>

2024-03-05 06:38 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/PunchItemQueries/GetPunchItemAttachments/GetPunchItemAttachmentsQuery.cs
> +    public string? FromIpAddress { get; }
FromIpAddress / ToIpAddress should not be nullable. Must set!

2024-03-05 06:42 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/PunchItemQueries/GetPunchItemAttachments/GetPunchItemAttachmentsQuery.cs
> +    public string? FromIpAddress { get; }
As far I can see now, the new constructor with 3 params are never used. The old constructor with one param should be removed, force using 3 params constructor in controller

2024-03-05 06:46 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/IAttachmentsService.cs
> +        string? fromIpAddress = null,
fromIpAddress / toIpAddress should not be nullable. Let CancellationToken be the last param

2024-03-05 13:48 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.IntegrationTests/TestFactory.cs
> +        BlobStorageMock.GetDownloadSasUri(
expr body

2024-03-05 13:55 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/appsettings.json
> +  "DevOnLocalhost": false
Move DevOnLocalhost inside Application section
Then expand the ApplicationOption class in Domain project
Finally inject ApplicationOption in src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs

2024-03-05 14:21 UTC, merged