Added controller for wo, implemented search
equinor/procosys-completion-api pull request #130
Opened 2024-04-17 07:26 UTC by Hatleskog

new controller for wo's, implemented wo search and tests.

2024-04-17 09:51 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/WorkOrderQueries/WorkOrderSearchQueryHandler.cs
> +            where workOrder.Plant.Equals(request.Plant)
remove ... global search filer handle this

2024-04-17 09:58 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/WorkOrderQueries/WorkOrderSearchQueryHandler.cs
> +            where workOrder.No.Contains(request.SearchPhrase)
Is it clarified with Business that the search should be Contains and not StartsWith? (Other similar places in preservation++ use StartsWith)

2024-04-17 10:02 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.IntegrationTests/CompletionContextExtension.cs
> +            "005");
use Guid.NewGuid().ToString().Substring(0, WorkOrder.NoLengthMax instead of 005 here

2024-04-17 10:07 UTC, janid1967 requested changes
See comments

2024-04-17 12:17 UTC, Hatleskog commented on src/Equinor.ProCoSys.Completion.Query/WorkOrderQueries/WorkOrderSearchQueryHandler.cs
> +            where workOrder.No.Contains(request.SearchPhrase)
Oenske fra FE her. Vi kan begynne med dette, saa eventuelt justere. 
Dette soeket skal utvides til aa ogsaa dekke description etc ogsaa innen kort tid.

2024-04-17 12:49 UTC, janid1967 requested changes

2024-04-17 12:49 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.IntegrationTests/KnownData.cs
> +    public static string OriginalWorkOrderNo4 => "004";
Rename OriginalWorkOrderNo4 to WorkOrderNo and OriginalWorkOrderNo5 to OriginalWorkOrderNo

Use dictionary to setup testdata for PlantA and PlantB. See 
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/7a1b1b58-86bb-4948-9bae-015dd424384a)

2024-04-18 08:24 UTC, janid1967 approved these changes

2024-04-18 08:34 UTC, merged