Added recalculation of CheckList for PunchListItem Creation, Deletion…
equinor/procosys-completion-api pull request #164
Opened 2024-06-05 07:25 UTC by agustarnason

… and certain Updates

2024-06-05 07:47 UTC, TordJoranger commented
I'm not sure if this enpoint in webapi returns right away, and if it returns at all.  Either way, we should not await it/require it to work.

2024-06-05 07:53 UTC, TordJoranger commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/ClearPunchItem/ClearPunchItemCommandHandler.cs
> +            await _checkListApiService.RecalculateCheckListStatus(punchItem.Plant, punchItem.CheckListGuid, cancellationToken);
after commit imo

2024-06-05 07:57 UTC, TordJoranger requested changes
Fire and forget

2024-06-05 09:15 UTC, janid1967 requested changes
In xxxPunchItemCommandHandlerTests.cs, add a new test assering that _checkListApiService.RecalculateCheckListStatus is called with correct parameteres for plant and CheckListGuid

2024-06-05 09:24 UTC, TordJoranger commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/ClearPunchItem/ClearPunchItemCommandHandler.cs
> +            await _checkListApiService.RecalculateCheckListStatus(punchItem.Plant, punchItem.CheckListGuid, cancellationToken);
yeah ok, disregard D:

2024-06-06 05:04 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/Attachments/AttachmentServiceTests.cs
remove unused usings

2024-06-06 05:06 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/Links/LinkServiceTests.cs
> +using static Microsoft.Graph.Constants;
remove (unused)

2024-06-06 05:08 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/ClearPunchItem/ClearPunchItemCommandHandlerTests.cs
> +        PunchItemUpdatedIntegrationEvent integrationEvent = null!;
remove thw whole Arrange block, integrationEvent not used

2024-06-06 05:10 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/ClearPunchItem/ClearPunchItemCommandHandlerTests.cs
> +        PunchItemUpdatedIntegrationEvent integrationEvent = null!;
same in other tests

2024-06-06 05:14 UTC, janid1967 approved these changes

2024-06-06 08:46 UTC, agustarnason commented
> I'm not sure if this enpoint in webapi returns right away, and if it returns at all. Either way, we should not await it/require it to work.


@TordJoranger @janid1967  I think the question in regards to the recalculation being awaited on, is whether or not we should do a rollback if we fail to recalculate, as I do agree that we don't really need to wait for the recalculation to be done for us to finish
If we don't care about the recalculation endpoint failing for whatever reason or not, we can just fire and forget, otherwise we probably should keep the await

2024-06-06 12:45 UTC, TordJoranger commented
> > I'm not sure if this enpoint in webapi returns right away, and if it returns at all. Either way, we should not await it/require it to work.
> 
> @TordJoranger @janid1967 I think the question in regards to the recalculation being awaited on, is whether or not we should do a rollback if we fail to recalculate, as I do agree that we don't really need to wait for the recalculation to be done for us to finish If we don't care about the recalculation endpoint failing for whatever reason or not, we can just fire and forget, otherwise we probably should keep the await

Ok, lets discuss it later, but we don't need to hold the pr over it.

2024-06-06 12:45 UTC, TordJoranger approved these changes

2024-06-06 12:52 UTC, merged