Add database sync auth token
equinor/procosys-completion-api pull request #179
Opened 2024-06-13 10:13 UTC by agustarnason

2024-06-13 10:54 UTC, TordJoranger commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Service/SyncTokenService.cs
> +            var result = await _app.AcquireTokenForClient([optionValues.Scope]).ExecuteAsync();
I would expect us to use AquireTokenAsync here

2024-06-13 11:09 UTC, TordJoranger approved these changes

2024-06-13 11:20 UTC, janid1967 requested changes
merge main in, SyncToPCS4Options is moved to Equinor.ProCoSys.Completion.Domain

2024-06-13 11:47 UTC, agustarnason commented
> merge main in, SyncToPCS4Options is moved to Equinor.ProCoSys.Completion.Domain

Are these change on main, or are they not yet merged?
I can't seem to find SyncToPCS4Options in Domain
Or did you mean for SyncToPCS4Options to be merged into ApplicationOptions?

2024-06-13 11:52 UTC, janid1967 approved these changes

2024-06-14 04:57 UTC, janid1967 commented
Please update https://statoildeveloper.visualstudio.com/Statoil.NextGenProCoSys/_wiki/wikis/Statoil.NextGenProCoSys.wiki/1910/Completion-API with new SyncToPCS4Options.Scope

2024-06-14 05:47 UTC, DownGoat approved these changes

2024-06-14 05:47 UTC, DownGoat commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Service/SyncBearerTokenHandler.cs
> +        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
We should cache this token

2024-06-14 05:59 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Service/SyncBearerTokenHandler.cs
> +        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
The same improvement should be done when we chat with main api too... that code is in Common repo ... if doing same improvement in Common for main api chatting, consider to make code general in Common so we don't need SyncBearerTokenHandler.cs at all (PS: Preservation chat with both Main api + Library api, and use same code to get token and create a http client)

2024-06-14 06:58 UTC, janid1967 requested changes

2024-06-14 06:58 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Service/SyncBearerTokenHandler.cs
> +                var checkList = await _syncTokenService.AquireTokenAsync();
rename to token

2024-06-14 08:07 UTC, agustarnason commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Service/SyncBearerTokenHandler.cs
> +        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
AquireTokenAsync itself calls AquireTokenAsync via IAuthenticatorOptions, and by default this function caches the token
The token is cached for as long as the token is valid, i.e. until expiration

2024-06-14 08:37 UTC, agustarnason commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Service/SyncBearerTokenHandler.cs
> +        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
If custom caching for this token is required, then it should probably be implemented in a different PR

2024-06-14 10:28 UTC, janid1967 approved these changes

2024-06-14 10:36 UTC, merged