Rearrange handler sync transactions
equinor/procosys-completion-api pull request #201
Opened 2024-07-02 09:10 UTC by agustarnason

2024-07-02 09:15 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Attachments/AttachmentService.cs
> +using Equinor.ProCoSys.Completion.Domain.AggregateModels.LinkAggregate;
remove

2024-07-02 09:17 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Attachments/AttachmentService.cs
> +            logger.LogError(e, "Error occurred while trying to Sync Create on Attachment with guid {guid}", attachment.Guid);
Sync Delete

2024-07-02 09:28 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
I don't see the solution, but AddAsync can't be as it is since the method don't commit, but it call syncToPCS4Service.SyncNewCommentAsync.

2024-07-02 09:32 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
Any suggestion @agustarnason ?

2024-07-02 09:32 UTC, agustarnason commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
Two solutions, we can either remove AddAsync and replace it with AddAndSaveAsync, or we can use a transaction for the places that use AddAsync, which seems to currently only be when we are rejecting a punch

2024-07-02 10:21 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Links/LinkService.cs
> +using Equinor.ProCoSys.Completion.Domain.AggregateModels.PunchItemAggregate;
remove

2024-07-02 10:21 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Links/LinkService.cs
> +using ServiceResult;
remove

2024-07-02 10:24 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
> +            _logger.LogError(e, "Error occurred while trying to Sync Update on PunchItem Comment with guid {guid}", commentEvent.Guid);
Error occurred while trying to Sync Create on Comment with guid {guid}

2024-07-02 10:25 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/ClearPunchItem/ClearPunchItemCommandHandler.cs
> +using Equinor.ProCoSys.Completion.MessageContracts;
remove

2024-07-02 10:27 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/DeletePunchItem/DeletePunchItemCommandHandler.cs
> +using Equinor.ProCoSys.Common.Misc;
remove

2024-07-02 10:31 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/DeletePunchItem/DeletePunchItemCommandHandler.cs
> +        {
Add a ToDo and add an issue in github: We also need to messageProducer.PublishAsync(new CommentDeletedByPunchItemIntegrationEvent s

2024-07-02 10:35 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/RejectPunchItem/RejectPunchItemCommandHandler.cs
> +        await _commentService.AddAsync(punchItem, punchItem.Plant, request.Comment, [rejectLabel], mentions, cancellationToken);
ref comment in AddAsync, we can't do this

2024-07-02 10:37 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UnclearPunchItem/UnclearPunchItemCommandHandler.cs
> +            _logger.LogError(e, "Error occurred while attempting to Recalculate the CheckListStatus for CheckList with Guid {guid}", punchItem.CheckListGuid);
Search and replace "Error occurred while attempting to" with "Error occurred while trying to" (6 occurrences)

2024-07-02 10:56 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/VerifyPunchItem/VerifyPunchItemCommandHandler.cs
> +        // AuditData must be set before publishing events due to use of Created- and Modified-properties
delete the if above, from line 44 - 47

2024-07-02 11:02 UTC, janid1967 requested changes
See comments
I will also like to see more unit tests .. we'll discuss which

2024-07-02 11:03 UTC, TordJoranger commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/DeletePunchItem/DeletePunchItemCommandHandler.cs
> +        {
I dont think we do. 
AttachmentDeletedByPunchItemIntegrationEvent is due to blobstorage

2024-07-03 05:11 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/RejectPunchItem/RejectPunchItemCommandHandlerTests.cs
> +        _unitOfWorkMock.When(x => x.SaveChangesAsync(default))
remove default

2024-07-03 05:15 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/RejectPunchItem/RejectPunchItemCommandHandlerTests.cs
> +        _unitOfWorkMock.ClearReceivedCalls();
remove all added _unitOfWorkMock.ClearReceivedCalls(); in all tests. Don't need, [TestInitialize] are run in front of each test => _unitOfWorkMock is new'ed again

2024-07-03 05:16 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/RejectPunchItem/RejectPunchItemCommandHandlerTests.cs
> +            .Do(x => throw new Exception("SaveChangesAsync error"));
replace x with _ (discard parameter). Do same fix in other test if code is equal there

2024-07-03 05:26 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/ClearPunchItem/ClearPunchItemCommandHandlerTests.cs
> +    public async Task HandlingCommand_ShouldRecalculate()
Remove this test, and the same test in 5 other classes. Duplicate of HandlingCommand_ShouldRecalculateChecklist()

2024-07-03 05:31 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/RejectPunchItem/RejectPunchItemCommandHandlerTests.cs
> +            .Do(x => throw new Exception("SaveChangesAsync error"));
A search'n replace of ".Do(x => throw new Exception" with ".Do(_ => throw new Exception" gave 52 replaces

2024-07-03 05:32 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/RejectPunchItem/RejectPunchItemCommandHandlerTests.cs
> +        _unitOfWorkMock.When(x => x.SaveChangesAsync(default))
Search'n and replace _unitOfWorkMock.When(x => x.SaveChangesAsync(default)) -> _unitOfWorkMock.When(x => x.SaveChangesAsync())

2024-07-03 05:33 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/ClearPunchItem/ClearPunchItemCommandHandlerTests.cs
> +using Equinor.ProCoSys.Completion.MessageContracts;
remove

2024-07-03 06:35 UTC, TordJoranger approved these changes

2024-07-03 07:34 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/RejectPunchItem/RejectPunchItemCommandHandlerTests.cs
> +        // Arrange
remove the Arrange part, integrationEvent not used

2024-07-03 07:35 UTC, janid1967 requested changes
See comments

2024-07-03 08:01 UTC, janid1967 approved these changes

2024-07-03 08:04 UTC, merged