504 - Servicebus - replace connection string with managed identity
equinor/procosys-completion-api pull request #259
Opened 2024-10-02 10:11 UTC by agustarnason

Moved from using Connection string for ServiceBus to using Managed Identity

https://github.com/equinor/cc-toolbox/issues/529

2024-10-02 11:43 UTC, DownGoat requested changes

2024-10-02 11:43 UTC, DownGoat commented on src/Equinor.ProCoSys.Completion.WebApi/DiModules/MassTransitModule.cs
> +                var credential = new DefaultAzureCredential();
You should pass in the TokenCredential we create in Program.cs

2024-10-02 11:45 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/DiModules/MassTransitModule.cs
> +                    throw new Exception("ServiceBusNamespace is not set in appsettings.json");
"ServiceBusNamespace is not properly configured"

2024-10-02 11:48 UTC, janid1967 approved these changes
After fixing what downgoat say, I approve it
**But: Do not merge yet since this is a breaking change. We will discuss how developer must also be responsible to ensure the change in config is propagated via infra-repo**

2024-10-03 11:03 UTC, DownGoat approved these changes

2024-10-10 06:22 UTC, merged