Replace BlobStorage ConnectionString with Managed Identity
equinor/procosys-completion-api pull request #266
Opened 2024-10-04 06:53 UTC by agustarnason

Removed BlobStorage connection string and replaced it with managed identity values instead

https://github.com/equinor/cc-toolbox/issues/526

2024-10-04 06:56 UTC, agustarnason commented
The procosys-common BlobStorage nuget package has to be updated and published first before this PR can be updated to use it

2024-10-04 10:15 UTC, DownGoat approved these changes

2024-10-09 05:08 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/appsettings.json
> +    "BlobStorageAccountKey": "",
Remove BlobStorageAccountKey?

2024-10-09 09:06 UTC, agustarnason commented
Tests are failing as this PR is waiting for BlobService nuget package to be updated first

2024-10-09 11:12 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/appsettings.json
> +    "BlobStorageAccountName": "",
sufficient with just AccountName since key already is inside BlobStorage block

2024-10-09 11:21 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
>      public AttachmentService(
Convert to primary constructor

2024-10-09 11:24 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
>              x.GetFullBlobPath(),
on line 119 and 126, rename x to attachment

2024-10-09 11:28 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/UserDelegationProvider/UserDelegationProvider.cs
> +        var endpoint = "https://" + options.CurrentValue.AccountName + _blobStorageUrlSuffix;
Here u perform the same logic as already in Common. _blobStorageUrlSuffix  should not be necessary here
U should reuse something from Common. A static thing on BlobStorageOptions?

2024-10-09 11:31 UTC, janid1967 requested changes
See comments

2024-10-09 11:44 UTC, agustarnason commented on src/Equinor.ProCoSys.Completion.Query/UserDelegationProvider/UserDelegationProvider.cs
> +        var endpoint = "https://" + options.CurrentValue.AccountName + _blobStorageUrlSuffix;
No, I did not implement any specific function to generate an endpoint like this, and to add it, we'd have to make another release for procosys-common/AzureBlobStorage to add it BlobStorageOptions

2024-10-10 05:12 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/UserDelegationProvider/UserDelegationProvider.cs
> +        var endpoint = "https://" + options.CurrentValue.AccountName + _blobStorageUrlSuffix;
Please do

2024-10-10 10:36 UTC, agustarnason commented on src/Equinor.ProCoSys.Completion.Query/UserDelegationProvider/UserDelegationProvider.cs
> +        var endpoint = "https://" + options.CurrentValue.AccountName + _blobStorageUrlSuffix;
Done in https://github.com/equinor/procosys-common/pull/45
Please go over when you have time

2024-10-10 11:25 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
> +    private readonly IReadOnlyContext _context = context;
Remove these 5 privates and use primary constructor variables

Did you use VS or Resharper tool to convert to primary constructor? If you do, the tool convert to use primary constructor variables and don't create these unnecessary privates

2024-10-10 11:27 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/Attachments/AttachmentService.cs
>              x.GetFullBlobPath(),
Still Attachment x on line 117

2024-10-10 11:28 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Query/UserDelegationProvider/UserDelegationProvider.cs
> +        var accountUrl = options.CurrentValue.AccountUrl;
nice

2024-10-10 11:33 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Query.Tests/Attachments/AttachmentServiceTests.cs
> +    private UserDelegationKey _userDelegationKeyMock;
remove

2024-10-10 11:33 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Query.Tests/Attachments/AttachmentServiceTests.cs
> +        _userDelegationKeyMock = Substitute.For<UserDelegationKey>();
var userDelegationKeyMock

2024-10-10 11:42 UTC, janid1967 approved these changes
Approved w minor approvements

2024-10-11 11:03 UTC, merged