Use correct punchitem.itemNo arg for PublishPunchItemCreatedIntegrati…
equinor/procosys-completion-api pull request #277
Opened 2024-10-16 13:12 UTC by Hatleskog

…onEvents

2024-10-17 05:25 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/DuplicatePunchItem/DuplicatePunchItemCommandHandler.cs
> +                    punchItem.ItemNo,
This change can't be correct!
But at line 68 there is a bug: it should be `new Property(nameof(PunchItem.ItemNo), punchCopy.ItemNo, ValueDisplayType.IntAsText`

2024-10-17 05:26 UTC, janid1967 requested changes
Se comment

2024-10-17 05:37 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/DuplicatePunchItem/DuplicatePunchItemCommandHandler.cs
> +                    punchItem.ItemNo,
Ahh ... now I see it. The first argument of PublishPunchItemCreatedIntegrationEventsAsync is sourceItemNo, used in History. But still, the bug at line 68 should be investigated.

How has then bug been reported? Is there an issue? Should we try to correct already made history or is that "impossible"? 

I guess bug on line 68 has made incorrect data in PCS4?

2024-10-17 09:39 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/DuplicatePunchItem/DuplicatePunchItemCommandHandler.cs
> +                    punchItem.ItemNo,
I investigate now

2024-10-18 10:37 UTC, DownGoat approved these changes

2024-10-18 10:53 UTC, merged