107922 - DB Synchronizer - completion to main - update
equinor/procosys-completion-api pull request #61
Opened 2023-11-23 11:01 UTC by arildbjerkenes

AB#107922

2023-11-27 07:02 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UpdatePunchItem/UpdatePunchItemCommandHandler.cs
> +        var transaction = await _unitOfWork.BeginTransaction(cancellationToken);
merge main-branch and use new _unitOfWork.BeginTransaction

2023-11-27 07:02 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UpdatePunchItem/UpdatePunchItemCommandHandler.cs
> +                // punchItem.AddDomainEvent(new PunchItemUpdatedDomainEvent(punchItem, changes));   // HAR KOMMENTERT UT MIDLERTIDIG PGA AV BUG SOM JAN INGE FIKSER
merge main-branch and uncomment

2023-11-27 07:03 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UpdatePunchItem/UpdatePunchItemCommandHandler.cs
> +            transaction.Commit();
merge main-branch and use new _unitOfWork.CommitTransaction

2023-11-27 07:03 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UpdatePunchItem/UpdatePunchItemCommandHandler.cs
> +            transaction.Rollback();
merge main-branch and use new _unitOfWork.RollbackTransactionAsync

2023-11-27 07:05 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UpdatePunchItem/UpdatePunchItemCommandHandler.cs
> +            _logger.LogError($"Error occured on update of punch item with guid {request.PunchItemGuid}.", ex);
occurred

2023-11-27 07:07 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Startup.cs
Undo changes in this file

2023-11-27 07:10 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/ColumnSyncConfig.cs
> +        public string? ValueConvertionMethod { get; set; }
ValueConversionMethod

2023-11-27 07:18 UTC, janid1967 commented
Use file-scoped namespaces in out new files. (I guess this is a setting in our Visual Studio)

2023-11-27 07:23 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/ColumnSyncConfig.cs
> +    public class ColumnSyncConfig
I preffer using prop with Get'er only, and init prop via constructors. Like this:
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/6cf64d1f-1ebc-4835-b381-da5e4dae6f42)

2023-11-27 07:30 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/IOracleDBExecutor.cs
> +        Task<int> ExecuteDBQueryCountingRows(string sqlQuery);
Rename all 3 methods by adding Async at end

2023-11-27 07:31 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/ColumnUpdate.cs
> +        public required string TargetColumnName { get; set; }
remove set'er and init by constructor as mentioned in ColumnSyncConfig.cs

2023-11-27 07:35 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/Equinor.ProCoSys.Completion.DbSyncToPCS4.csproj
> +  <PropertyGroup>
Why do this differ from other csproj-files?
<TreatWarningsAsErrors>true</TreatWarningsAsErrors> should be added.
Can <ImplicitUsings> and <OutputType> be removed?

I guess we don't need UserSecrets file both here and in WebApi project, remove <UserSecretsId>

2023-11-27 07:39 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/OracleDBExecutor.cs
> +            using var connection = new OracleConnection(_dbConnStr);
await using (same for whole class)

2023-11-27 07:49 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/SyncMappingConfig.cs
> +        public enum DataColumnType
move to separate file

2023-11-27 07:51 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/SyncUpdateHandler.cs
> +        public async Task HandleAsync(object entity, SyncMappingConfig syncMappingConfig, CancellationToken cancellationToken = default)
cancellationToken should be passed down to oracle method where Async methods exists with cancellationToken

2023-11-27 08:17 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/OracleDBExecutor.cs
> +    public class OracleDBExecutor : IOracleDBExecutor
We need to discuss if it is correct to open new connection inside each methods here.
Should the connection be opened "earlier", so all queries + final write is performed inside the very same connection

2023-11-27 08:20 UTC, janid1967 commented
We need to discuss the level of unit and/or integration tests

2023-11-27 08:24 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/SyncUpdateHandler.cs
> +            var primaryKeyConfig = syncMappingList.Where(config => config.IsPrimaryKey == true).Single();
syncMappingList.Single(config => config.IsPrimaryKey);

Consider to use SingleOrDefault, and check if null afterwards. This to give a better exception if Single fails. The exception can then explain something as "The configuration need a single column where IsPrimaryKey is set"

2023-11-27 12:53 UTC, janid1967 commented
Console.WriteLine må erstattes med bruk av ILogger<>

2023-11-28 07:20 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/OracleDBExecutor.cs
> +            if (_dbConnStr == null)
do this in constructor, same in ExecuteDBQueryCountingRows

2023-11-28 14:23 UTC, arildbjerkenes commented on src/Equinor.ProCoSys.DbSync/OracleDBExecutor.cs
> +    public class OracleDBExecutor : IOracleDBExecutor
Jeg har for nå implementere at starter en transaksjon, hvor vi da utfører commit og evt. rollback. Da kan jeg også sjekke at korrekt antall rader er oppdatert. Vi kan lage en egen PBI på å bygge om OracleDBExecutor, slik at vi gjenbruker connection, og muligens også transaciton. Må tenke litt mer på hvordan det er best å gjøre dette.

2023-11-29 18:27 UTC, TordJoranger commented on src/Equinor.ProCoSys.DbSync/ValueConversion.cs
> +                    if (sourceValue == null || sourceValue.ToString() == "0")
This assumes null == false. This is not always the case.

2023-11-29 18:53 UTC, TordJoranger commented on DbSyncToPCS4/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
this is added too the root folder of the solution. Test project should be next to other test projects in test folder

2023-11-29 18:55 UTC, TordJoranger commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +namespace DbSyncToPCS4
fix namespace. (look other tests files)

2023-11-29 18:57 UTC, TordJoranger commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +            Assert.AreEqual<string>(actualSqlUpdateStatement, _expectedSqlUpdateStatement);
swap arguments, and <string> is not needed.

2023-11-29 19:06 UTC, TordJoranger commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +        public async Task SyncToPCS4Service_ShouldRunSuccessfully_WhenInputIsCorrect()
I don't think this test adds any value. How would I break it?
 Also would need its own test class.

2023-11-29 19:13 UTC, TordJoranger commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +    public class SyncUpdateHandlerTests
![image](https://github.com/equinor/procosys-completion-api/assets/22048868/00734f70-f3cd-4999-b48c-34b01ede0a3f)

2023-11-29 19:17 UTC, TordJoranger commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +        public async Task BuildSqlUpdateStatement_ShouldReturnException_WhenMissingPrimaryKey()
"WhenConfigIsMissingPrimaryKey"

2023-11-29 19:17 UTC, TordJoranger commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +        public async Task BuildSqlUpdateStatement_With_ConvertionMethodNotExists()
better test name

2023-11-29 19:19 UTC, TordJoranger commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +        public async Task BuildSqlUpdateStatement_ShouldReturnException_WhenMissingProperty()
All tests expecting an Exception without any other requirements, are very prone to false positives. 
Can we check for the specific exception?

2023-11-29 19:27 UTC, TordJoranger commented
We're missing tests for:
 OracleDbExecutor(Minumum tests that break if we break the transaction logic).
 ValueConverion.cs 
 SyncMappingConfig.cs
 Integrationtests

2023-11-29 19:30 UTC, TordJoranger commented on src/Equinor.ProCoSys.DbSync/SyncToPCS4Service.cs
> +            _syncMappingConfig = new SyncMappingConfig();
DI

2023-11-29 19:43 UTC, TordJoranger commented
I think the initial idea of updating the whole object regardless of amount of changes every time, does not really hold water when we do updates this way. 
We don't really ever do this, even when we have a post endpoint that "overwrites all fields" Entity framework only updates changed fields "under the hood"

2023-11-29 21:42 UTC, TordJoranger requested changes
I can not approve this PR in its current state.
I do not think this code lives up to the standard of the rest of the code base.

My recommendation is to not merge this, and rather start over, and solve it in a more standard way, that is more in line with test rest of the code base.

2023-11-30 06:26 UTC, janid1967 commented on src/Equinor.ProCoSys.DbSync/OracleDBExecutor.cs
> +            using var connection = new OracleConnection(_dbConnStr);
await using (all places in class for both connection and transaction)

2023-11-30 09:30 UTC, arildbjerkenes commented on src/Equinor.ProCoSys.DbSync/ValueConversion.cs
> +                    if (sourceValue == null || sourceValue.ToString() == "0")
Good catch! Was uncertain about this. I assume that boolean columns will allways be 'non null'? Maybe we should just throw an exception here?

2023-11-30 09:42 UTC, arildbjerkenes commented on DbSyncToPCS4/SyncUpdateHandlerTests.cs
> +    public class SyncUpdateHandlerTests
I don't think it should break the tests. You have added a syncronization for 'WillThisBreakTests?'. Fine, if you need it. It has nothing to do with the testobjects. The system does not really care about the sequence of the rows in the csv file.

2024-01-11 13:42 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/ISyncToPCS4Service.cs
> +    Task SyncNewObjectAsync(string sourceObjectName, object sourceObject, string plant, CancellationToken cancellationToken = default);
remove = default on these 3 methods

2024-01-11 13:43 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Pcs4Repository.cs
> +        if (_dbConnStr == null)
if (_dbConnStr is null)

2024-01-11 13:45 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Pcs4Repository.cs
> +            if (result != null && result is long)
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/0226b191-6c9d-4d9a-8f9f-252a2aaa26aa)

2024-01-11 13:46 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/PropertyMapping.cs
> +        if (sourcePropertyValue != null && sourcePropertyNameParts.Length > 1)
replace != with is not

2024-01-11 13:47 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/PropertyMapping.cs
> +            sourceProperty = sourcePropertyValue?.GetType().GetProperty(sourcePropertyNameParts[1]);
sourcePropertyValue.GetType()  (remove the ?)

2024-01-11 13:48 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlDeleteStatementBuilder.cs
> +        var primaryKeyValue = PropertyMapping.GetSourcePropertyValue(sourceObjectMappingConfig.PrimaryKey.SourcePropertyName, sourceObject);
format 2 long lines

2024-01-11 13:52 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlDeleteStatementBuilder.cs
> +public class SqlDeleteStatementBuilder(IPcs4Repository oracleDBExecutor)
rename oracleDBExecutor to pcs4Repository (do the same for all variables of type IPcs4Repository, also in SqlInsertStatementBuilder + SqlUpdateStatementBuilder )

2024-01-11 13:55 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlDeleteStatementBuilder.cs
> +    private readonly IPcs4Repository _oracleDBExecutor = oracleDBExecutor;
remove _oracleDBExecutor  and use oracleDBExecutor from prim constructor at line 25
(, also in SqlInsertStatementBuilder + SqlUpdateStatementBuilder)

2024-01-11 13:57 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlInsertStatementBuilder.cs
> +    public async Task<(string sqlStatement, DynamicParameters sqlParameters)> BuildAsync(ISourceObjectMappingConfig sourceObjectMappingConfig, object sourceObject, string plant, CancellationToken can
format long line, same on line 23+24

2024-01-11 13:57 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlInsertStatementBuilder.cs
> +            if (propertyMapping.TargetFixedValue == null)
is null

2024-01-11 13:58 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlInsertStatementBuilder.cs
> +                if (targetColumnValue != null)
is not null

2024-01-11 13:58 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlInsertStatementBuilder.cs
> +                    parameterValuesForInsert.Add($":{propertyMapping.TargetColumnName}"); //We use prepared statment (with parametrized sql statement).
statement (also on line 37)

2024-01-11 13:59 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlParameterConversionHelper.cs
> +        if (value == null)
is null

2024-01-11 13:59 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlParameterConversionHelper.cs
> +        IPcs4Repository oracleDBExecutor,
rename to pcs4Repository

2024-01-11 14:02 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlParameterConversionHelper.cs
> +                else
remove redundant else

2024-01-11 14:04 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlParameterConversionHelper.cs
> +        if (guid == null || !guid.HasValue)
simplify to 
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/e904d91b-4d1e-47a1-918e-13922d5a4e8e)

2024-01-11 14:07 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlParameterConversionHelper.cs
> +        var sqlQuery = $"select Library_id from library where procosys_guid = :procosys_guid";
remove the extra $ .... do it fort all methods below, without the last one

2024-01-11 14:08 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlDeleteStatementBuilder.cs
> +        CancellationToken cancellationToken = default)
remove the default param .. also for  also in SqlInsertStatementBuilder + SqlUpdateStatementBuilder

2024-01-11 14:10 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlUpdateStatementBuilder.cs
> +        if (primaryKeyTargetValue == null)
is null

2024-01-11 14:12 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SyncToPCS4Service.cs
> +    readonly IPcs4Repository _pcs4Repository = oracleDBExecutor;
remove and use from primary constructor. Rename the oracleDBExecutor in constructor to pcs4Repository

2024-01-11 14:12 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
> +        IUnitOfWork unitOfWork,
Curious: Why has IUnitOfWork been moved from constructor to method parameter?

2024-01-11 14:13 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SyncToPCS4Service.cs
format long lines in class

2024-01-11 14:36 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UnclearPunchItem/UnclearPunchItemCommandHandler.cs
> +            _logger.LogError("Error occurred on update of punch item with guid {PunchItemGuid}.", request.PunchItemGuid);
Do you want to keep a generic update error message, or specify that the error happened for Unclear operation?

2024-01-11 14:41 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/VerifyPunchItem/VerifyPunchItemCommandHandler.cs
> +            if (punchItem == null)
is null

2024-01-12 06:21 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/NestedSourceTestObject.cs
> +public class NestedSourceTestObject(Guid guid)
simplify to record
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/a211223b-36d0-44d0-b0e1-b25037d4aa2f)

2024-01-12 06:22 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SourceTestObject.cs
> +public class SourceTestObject(
simplify to record
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/0e5a1aa4-ba9f-4bb3-a2df-46c896d39cd4)

2024-01-12 06:23 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
Add     <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

2024-01-12 06:24 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SourceTestObjectMissingPrimaryKey.cs
> +public class SourceTestObjectMissingPrimaryKey(
simplify to record

2024-01-12 06:26 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlDeleteStatementBuilderTests.cs
> +        _dut = new SqlDeleteStatementBuilder(_oracleDBExecutorMock);
expr body

2024-01-12 06:28 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlDeleteStatementBuilderTests.cs
> +    public async Task BuildSqlDeleteStatement_ShouldReturnSqlStatmeent_WhenInputIsCorrect()
Rename Statmeent to Statment (run search-and-replace ... i find 4 for them)

2024-01-12 06:35 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SyncToPCS4Service.cs
> +    public async Task SyncNewObjectAsync(string sourceObjectName, object sourceObject, string plant, CancellationToken cancellationToken = default)
remove default param in all methods in this class

2024-01-12 06:38 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlInsertStatementBuilderTests.cs
> +    public async Task BuildSqlInsertStatement_ShouldReturnSqlStatment_WhenSourceObjectHasNullValues()
Statement_

2024-01-12 06:40 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlDeleteStatementBuilderTests.cs
> +        var (actualSqlUpdateStatement, actualSqlParams) = await _dut.BuildAsync(_testObjectMappingConfig, _sourceTestObject, default);
For calls to BuildAsync and SyncObjectUpdateAsync in this class (+ SqlInsertStatementBuilderTests.cs and SqlUpdateStatementBuilderTests.cs), use null! for plant param, and default for cancellationToken param

2024-01-12 06:42 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlInsertStatementBuilderTests.cs
> +        _dut = new SqlInsertStatementBuilder(_oracleDBExecutorMock);
expr body

2024-01-12 06:45 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlInsertStatementBuilderTests.cs
> +        var sourceTestObject = new SourceTestObject(null, _testGuid, null, null, null, false, null, null, null, null, null, null);
The param for NestedSourceTestObject should be null! (or make NestedSourceTestObject nullable in SourceTestObject)

2024-01-12 06:45 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlStatementBuilderTestsBase.cs
> +    protected IPcs4Repository _oracleDBExecutorMock;
rename to pcs4Repository

2024-01-12 06:49 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlStatementBuilderTestsBase.cs
> +    protected readonly Guid _testGuid = new Guid("805519D7-0DB6-44B7-BF99-A0818CEA778E");
simpify in this class:
1) rename all protected readonly vars to PascalCase (sample: SourceObjectNameMissingConfig )
1) use target-typed new for all Guid and DateTime (sample: protected readonly Guid TestGuid = new("805519D7-0DB6-44B7-BF99-A0818CEA778E"))

2024-01-12 06:49 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlUpdateStatementBuilderTests.cs
> +        _dut = new SqlUpdateStatementBuilder(_oracleDBExecutorMock);
expr body

2024-01-12 06:51 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlUpdateStatementBuilderTests.cs
> +        _sourceTestObject = new SourceTestObject(null, _testGuid, null, null, null, false, null, null, null, null, null, null);
The param for NestedSourceTestObject should be null! (or make NestedSourceTestObject nullable in SourceTestObject)

2024-01-12 06:55 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/TestObjectMappingConfig.cs
> +    public PropertyMapping PrimaryKey { get; } = new PropertyMapping("TestGuid", PropertyType.Guid, "TestGuid", null, null, false);
target-typed new

2024-01-12 06:56 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/TestObjectMappingConfig.cs
> +    public TestObjectMappingConfig() => PropertyMappings = new List<PropertyMapping>
Convert constructor to member initializer. When I do it, my VS transform to:
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/f3d8e817-e3d8-4a94-8cce-11614d2da3ef)

2024-01-12 06:58 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/TestObjectMissingPropMappingConfig.cs
> +    public TestObjectMissingPropMappingConfig() => PropertyMappings = new List<PropertyMapping>
Convert constructor to member initializer

2024-01-12 06:58 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/TestObjectMissingPropMappingConfig.cs
> +    public PropertyMapping PrimaryKey { get; } = new PropertyMapping("TestGuid", PropertyType.Guid, "TestGuid", null, null, false);
target-typed new

2024-01-12 07:04 UTC, janid1967 requested changes
See comments

2024-01-12 07:30 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.Domain.Tests/IntegrationEvents/PunchItemEvents/PunchItemUpdatedIntegrationEventTests.cs
> +        AssertRequiredProperties(_punchItem, integrationEvent);
It seems Guid values are not verified, is this by design?
I.e. RaisedByOrgGuid, CheckListGuid, etc

2024-01-12 07:39 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
> +        _commentRepository.Add(comment);
AddAsync is now splitted into 2 methods: Add and AddAndSaveAsync
Add don't perform save, which was the only async method
This also mean that caller method of Add as responsible for performing the save (which is done in the command handler for reject .... A reject perform both and update on the punch itself + adding a comment -> We want to save both changes in the very same save in the unitOfWork created in the command hander **which also is in an open transaction**)

Agree @jsoi-eq ?

2024-01-12 07:42 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
> +        IUnitOfWork unitOfWork,
See my answer on "Curious: Why Add and not AddAsync?" below

2024-01-12 07:43 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/UpdatePunchItemCategory/UpdatePunchItemCategoryCommandHandlerTests.cs
> +    public async Task HandlingCommand_ShouldPublishCorrectHistoryEvent()
Curious, why  do we have a ShouldPublishCorrectHistoryEvent and not a ShouldPublishCorrectUpdatedPunchEvent?

2024-01-12 07:46 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Command/PunchItemCommands/UnclearPunchItem/UnclearPunchItemCommandHandler.cs
> +            _logger.LogError("Error occurred on update of punch item with guid {PunchItemGuid}.", request.PunchItemGuid);
I'll specify

2024-01-12 08:04 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/UpdatePunchItemCategory/UpdatePunchItemCategoryCommandHandlerTests.cs
> +    public async Task HandlingCommand_ShouldPublishCorrectHistoryEvent()
I'll add in all xxxCommandHandlerTests.cs

2024-01-12 08:08 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.Command/Comments/CommentService.cs
> +        _commentRepository.Add(comment);
It was more of why we are not using AddAsync method in EntityRepository with Set.AddAsync, similar to
    public virtual void Add(TEntity entity) =>
        Set.Add(entity);
Note, this is far from my expertise, just being curious.

2024-01-12 08:11 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/UpdatePunchItemCategory/UpdatePunchItemCategoryCommandHandlerTests.cs
> +    public async Task HandlingCommand_ShouldPublishCorrectHistoryEvent()
Because existing HandlingCommand_ShouldPublishUpdatedPunchEvent Assert that we receive one call to PublishUpdatedEventAsync with a particular Punch, which proof that this is "CorrectUpdatedPunchEvent"

However, HandlingCommand_ShouldPublishUpdateToHistory, just Assert that we receive a PublishUpdatedEventAsync with **any** combination of arguments, and rather test in HandlingCommand_ShouldPublishCorrectHistoryEvent that 
PublishUpdatedEventAsync was called with **correct** arguments

@jsoi-eq Any suggestion to improvement (on test-method names?) to avoid confusion?

2024-01-12 08:16 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.Command.Tests/PunchItemCommands/UpdatePunchItemCategory/UpdatePunchItemCategoryCommandHandlerTests.cs
> +    public async Task HandlingCommand_ShouldPublishCorrectHistoryEvent()
No, I don't think we make anything more out of it.

2024-01-12 08:40 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Equinor.ProCoSys.Completion.DbSyncToPCS4.csproj
> +    <PackageReference Include="MSTest.TestAdapter" Version="3.0.2" />
remove MSTest.TestAdapter and MSTest.TestFramework ... test packages should not be required in "production" code

2024-01-15 20:58 UTC, arildbjerkenes commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/TestObjectMappingConfig.cs
> +    public TestObjectMappingConfig() => PropertyMappings = new List<PropertyMapping>
Have changed this to: 

  public TestObjectMappingConfig() => PropertyMappings =
      [

2024-01-16 06:36 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Equinor.ProCoSys.Completion.DbSyncToPCS4.csproj
> +    <TargetFramework>net8.0</TargetFramework>
Add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`

2024-01-16 06:49 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SourceTestObject.cs
> +public class SourceTestObject(
Simplyfy even more to just primary constructor?

2024-01-16 06:50 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SourceTestObjectMissingPrimaryKey.cs
> +public class SourceTestObjectMissingPrimaryKey(
Simplify even more to just primary constructor?

2024-01-16 06:53 UTC, janid1967 approved these changes
Approved with some minor improvement suggestions. See comments

2024-01-16 07:21 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/MappingConfig/PunchItemMappingConfig.cs
> +    public PropertyMapping PrimaryKey { get; } = new PropertyMapping("Guid", PropertyType.Guid, "Procosys_guid", null, null, false);
Redundant type specification

2024-01-16 07:29 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Pcs4Repository.cs
> +        if (_dbConnStr is null)
Perhaps consider validation at startup?
https://www.milanjovanovic.tech/blog/adding-validation-to-the-options-pattern-in-asp-net-core
Could have as a todo for later.

2024-01-16 07:38 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlDeleteStatementBuilder.cs
> +        return (deleteStatement.ToString(), sqlParameters);
Using DynamicParameters takes care of sql injection risks, is that correct?

2024-01-16 07:40 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlDeleteStatementBuilder.cs
> +        if (primaryKeyTargetValue is null)
Checking primaryKeyTargetValue for null, but not primaryKeyValue, any reason for that?

2024-01-16 07:47 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlParameterConversionHelper.cs
> +        if (propertyMapping.ValueConversion != null)
is not null

2024-01-16 08:01 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlUpdateStatementBuilder.cs
> +            throw new Exception("Not able to build update statement. Primary key value is null.");
Primary key _target_ value?

2024-01-16 08:10 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SyncToPCS4Service.cs
> +            "PunchItem" => new PunchItemMappingConfig(),
Agree, and use that constant in commandhandlers as here
![image](https://github.com/equinor/procosys-completion-api/assets/19545528/7cbad350-0173-4b47-b121-9e1e79636408)

2024-01-16 08:14 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlDeleteStatementBuilderTests.cs
> +        foreach (var expectedParam in _expectedSqlParameters)
Move foreach block to private method with descriptive name?

2024-01-16 08:14 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlDeleteStatementBuilderTests.cs
> +            else
If you are testing two different scenarios, maybe they deserve two different tests?

2024-01-16 08:17 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlInsertStatementBuilderTests.cs
> +        foreach (var expectedParam in _expectedSqlParameters)
Same comments as SqlDeleteStatementBuilderTests

2024-01-16 08:18 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlInsertStatementBuilderTests.cs
> +    public async Task BuildSqlInsertStatement_ShouldReturnSqlStatment_WhenInputIsCorrect()
Statment -> Statement. Sorry. OCD.

2024-01-16 09:03 UTC, jsoi-eq commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlUpdateStatementBuilderTests.cs
> +        foreach (var expectedParam in _expectedSqlParameters)
Same comment as SqlDeleteStatementBuilderTests

2024-01-16 09:06 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/PropertyMapping.cs
> +    public static object? GetSourcePropertyValue(string configuredPropertyName, object sourceObject)
Are there any unit tests for this method?

2024-01-16 14:09 UTC, arildbjerkenes commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Pcs4Repository.cs
> +        if (_dbConnStr is null)
The Pcs4Repository is created as a singleton, by the dependency injection system. A assumed that the instance is created at startup. Not?

2024-01-16 14:10 UTC, arildbjerkenes commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SqlDeleteStatementBuilder.cs
> +        return (deleteStatement.ToString(), sqlParameters);
Yes, it does.

2024-01-16 14:34 UTC, jsoi-eq commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Pcs4Repository.cs
> +        if (_dbConnStr is null)
Umm yes, but I'm not following on what that has to do with validating that _dbConnStr is not null?

2024-01-16 14:37 UTC, arildbjerkenes commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SyncToPCS4Service.cs
> +            "PunchItem" => new PunchItemMappingConfig(),
So far the DbSyncToPCS4 does not have relations to any other projects in completion. This is done to make it simple to move out, if needed. I think we should keep it like this for now, and adjust later when we know more.

2024-01-16 14:42 UTC, arildbjerkenes commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/Pcs4Repository.cs
> +        if (_dbConnStr is null)
After discussion with Jostein, we will not do this now (the tool might be moved out of the project)

2024-01-16 15:03 UTC, arildbjerkenes commented on src/tests/Equinor.ProCoSys.Completion.DbSyncToPCS4.Tests/SqlDeleteStatementBuilderTests.cs
> +            else
We are not testing two different scenarios here. We loop through the list of parameters, and verify that each of them is correct. We have to convert integers to be able to compare. I have extracted this to a private method, and have added a comment. Hope this is more readable now.

2024-01-17 06:33 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SyncToPCS4Service.cs
> +            "PunchItem" => new PunchItemMappingConfig(),
I don't agree. This has nothing to do with moving the code or not. The constant should be created inside SyncToPCS4Service.cs. I fix, it will cost me 2 minutes

2024-01-17 06:39 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/SyncToPCS4Service.cs
> +            "PunchItem" => new PunchItemMappingConfig(),
Fixed

2024-01-17 11:02 UTC, arildbjerkenes commented on src/Equinor.ProCoSys.Completion.DbSyncToPCS4/PropertyMapping.cs
> +    public static object? GetSourcePropertyValue(string configuredPropertyName, object sourceObject)
Added.

2024-01-17 11:04 UTC, merged