103926 Message subscriber infrastructure/Project Subscription
equinor/procosys-completion-api pull request #76
Opened 2023-12-15 15:04 UTC by TordJoranger

2023-12-15 15:05 UTC, TordJoranger commented on src/Equinor.ProCoSys.Completion.Infrastructure/CompletionContext.cs
> +        => modelBuilder.AddTransactionalOutboxEntities();
this does the same as the 3 lines over, convince method from MT

2023-12-18 06:14 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        Pcs4LastUpdated = lastUpdated;
ProCoSys4LastUpdated

2023-12-18 06:17 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Domain/AggregateModels/ProjectAggregate/Project.cs
> +    public DateTime Pcs4LastUpdated { get; set; }
Add .HasConversion(CompletionContext.DateTimeKindConverter) in ProjectConfiguration (see PunchItemConfiguration)

2023-12-18 06:25 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/DiModules/ApplicationModule.cs
remove blank line

2023-12-18 06:28 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/DiModules/ApplicationModule.cs
> +                    opts.Converters.Add(new OracleGuidConverter());
why do we need the OracleGuidConverter?

2023-12-18 06:35 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        Pcs4LastUpdated = lastUpdated;
Check for Kind.Utc, throw exception if not ... search through solution and replace , DateTime.Now with , DateTime.UtcNow where used in Project constructor (Seeder.cs ++)

2023-12-18 06:37 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +        ICurrentUserSetter currentUserSetter, IOptions<CompletionAuthenticatorOptions> options)
split into 2 lines

2023-12-18 06:39 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +        _options = options;
_completionApiObjectId = _options.Value.CompletionApiObjectId

2023-12-18 06:40 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +        ICurrentUserSetter currentUserSetter, IOptions<CompletionAuthenticatorOptions> options)
Use IOptionsMonitor<>

2023-12-18 06:46 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +                _logger.LogWarning("Project Message Ignored because a newer LastUpdated already exits in db:" +
\n behind db: and remove space in front of MessageId at next line
Split " MessageId: {MessageId} \n ProCoSysGuid {ProCoSysGuid} \n " into 2 lines, with \n as last char

2023-12-18 06:47 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +        if (projectEvent.Description != null)
is not null

2023-12-18 06:48 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +         => new(projectEvent.Plant, projectEvent.ProCoSysGuid, projectEvent.ProjectName,projectEvent.Description?? projectEvent.ProjectName, projectEvent.LastUpdated);
long line, split so one param on each line

2023-12-18 06:49 UTC, janid1967 commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +public record ProjectEvent(string EventType, string? Description,
move to its own file

2023-12-18 06:54 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +    private readonly IOptions<CompletionAuthenticatorOptions> _optionsMock = Substitute.For<IOptions<CompletionAuthenticatorOptions>>();
long line

2023-12-18 06:54 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +        _projectEventConsumer = new ProjectEventConsumer(Substitute.For<ILogger<ProjectEventConsumer>>(), _projectRepoMock,
one param on each line

2023-12-18 06:57 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +    public ProjectEventConsumerTests() =>
who both constructor AND Setup?
Prefer to remove constructor and move init of _projectEventConsumer  to Setup

2023-12-18 06:59 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +    public async Task Consume_ShouldRemoveProject_IfMessageContainsDelete()
IfBehaviorIsDelete

2023-12-18 07:01 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +        var testEvent = new ProjectEvent("", "project", false, DateTime.MinValue, "plant", Guid.Empty,
Prefer to see one param on each line (when not all params fit on one line) ... this through whole this class

2023-12-18 07:04 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +
I like to see more positive tests:
1) Test the update
2) Test the add with description
3) Test the add without description (the edge case)

2023-12-18 07:04 UTC, janid1967 requested changes
See comments

2023-12-18 08:42 UTC, TordJoranger commented on src/Equinor.ProCoSys.Completion.WebApi/Synchronization/ProjectEventConsumer.cs
> +         => new(projectEvent.Plant, projectEvent.ProCoSysGuid, projectEvent.ProjectName,projectEvent.Description?? projectEvent.ProjectName, projectEvent.LastUpdated);
la gå :)

2023-12-19 08:45 UTC, TordJoranger commented on src/Equinor.ProCoSys.Completion.Domain/AggregateModels/ProjectAggregate/Project.cs
> +        Pcs4LastUpdated = lastUpdated;
we discussed this, wont fix for now, but will add explaining comment

2023-12-19 09:51 UTC, TordJoranger commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +    public ProjectEventConsumerTests() =>
because of nullability constraints

2023-12-19 10:44 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +    public async Task Consume_WorksAsExpected_WhenAddingNewProject()
Consume_ShouldAddNewProject_WhenProjectNotExists

2023-12-19 10:45 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +    public async Task Consume_WorksAsExpected_WhenUpdatingProject()
Consume_ShouldUpdateExistingProject_WhenProjectExists

2023-12-19 10:45 UTC, janid1967 commented on src/tests/Equinor.ProCoSys.Completion.WebApi.Tests/Synchronization/ProjectEventConsumerTests.cs
> +    public async Task Consume_UsedProjectNameAsDescription_WhenDescriptionIsNull()
Consume_ShouldUseProjectNameAsDescription_WhenDescriptionIsNull()

2023-12-19 10:46 UTC, janid1967 approved these changes
Approved with minor rename suggestions of test methods

2023-12-19 10:56 UTC, merged